#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — repository-specific prompt generation.
# Keep the wizard library above this marker identical to the skill template.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

merge_error() {
  printf 'Cannot merge aside sections: %s\n' "$1" >&2
  return 1
}

scan_headings() {
  local file="$1" line content fence='' marker info title
  local heading_re='^ {0,3}(#{1,6})([[:blank:]]+(.*))?$'
  local fence_re='^ {0,3}(`{3,}|~{3,})(.*)$'
  local closing_re='(^|[[:blank:]]+)#+[[:blank:]]*$'
  HEADING_LINES=(); HEADING_LEVELS=(); HEADING_TITLES=()
  LINE_COUNT=0; FIRST_CONTENT_LINE=0; LAST_CONTENT_LINE=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    LINE_COUNT=$((LINE_COUNT + 1))
    if [[ "$line" =~ [^[:space:]] ]]; then
      if (( FIRST_CONTENT_LINE == 0 )); then FIRST_CONTENT_LINE=$LINE_COUNT; fi
      LAST_CONTENT_LINE=$LINE_COUNT
    fi
    content="$line"
    while [[ "$content" == *$'\r' ]]; do content="${content%$'\r'}"; done
    if [[ -n "$fence" ]]; then
      if [[ "$content" =~ $fence_re ]]; then
        marker="${BASH_REMATCH[1]}"; info="${BASH_REMATCH[2]}"
        if [[ "${marker:0:1}" == "${fence:0:1}" && ${#marker} -ge ${#fence} && "$info" =~ ^[[:space:]]*$ ]]; then
          fence=''
        fi
      fi
      continue
    fi
    if [[ "$content" =~ $fence_re ]]; then
      marker="${BASH_REMATCH[1]}"; info="${BASH_REMATCH[2]}"
      if [[ "$marker" != '`'* || "$info" != *'`'* ]]; then fence="$marker"; fi
      continue
    fi
    if [[ "$content" =~ $heading_re ]]; then
      marker="${BASH_REMATCH[1]}"; title="${BASH_REMATCH[3]}"
      if [[ "$title" =~ $closing_re ]]; then title="${title%"${BASH_REMATCH[0]}"}"; fi
      title="${title#"${title%%[![:blank:]]*}"}"
      title="${title%"${title##*[![:blank:]]}"}"
      HEADING_LINES+=("$LINE_COUNT")
      HEADING_LEVELS+=("${#marker}")
      HEADING_TITLES+=("$title")
    fi
  done < "$file"
  if [[ -n "$fence" ]]; then
    merge_error 'Unclosed fenced code block; refusing an ambiguous section merge'
    return 1
  fi
}

ensure_final_newline() {
  if [[ "$(tail -c 1 "$1" | wc -l)" -eq 0 ]]; then printf '\n' >> "$1"; fi
}

merge_sections() (
  set -euo pipefail
  export LC_ALL=C
  local original="$1" output="$2" aside result section old_section next
  local start level title core_lines source_blanks match end index existing_blanks
  shift 2
  local work_dir
  work_dir="$(mktemp -d "${TMPDIR:-/tmp}/agent-merge.XXXXXX")"
  trap 'rm -rf "$work_dir"' EXIT
  trap 'exit 130' INT
  trap 'exit 143' TERM
  result="$work_dir/result"
  cp "$original" "$result"
  for aside in "$@"; do
    if ! iconv -f UTF-8 -t UTF-8 "$aside" >/dev/null; then
      merge_error "Cannot read UTF-8 aside: $aside"; exit 1
    fi
    scan_headings "$aside"
    if (( ${#HEADING_LINES[@]} == 0 )); then
      merge_error 'Aside must start with an ATX heading'; exit 1
    fi
    start="${HEADING_LINES[0]}"; level="${HEADING_LEVELS[0]}"; title="${HEADING_TITLES[0]}"
    if (( FIRST_CONTENT_LINE != start )); then
      merge_error 'Aside must contain one main heading and its child sections'; exit 1
    fi
    for (( index=1; index<${#HEADING_LINES[@]}; index++ )); do
      if (( HEADING_LEVELS[index] <= level )); then
        merge_error 'Aside must contain one main heading and its child sections'; exit 1
      fi
    done
    section="$work_dir/section"
    tail -n "+$start" "$aside" > "$section"
    ensure_final_newline "$section"
    scan_headings "$section"
    core_lines=$LAST_CONTENT_LINE
    source_blanks=$((LINE_COUNT - LAST_CONTENT_LINE))
    if ! iconv -f UTF-8 -t UTF-8 "$result" >/dev/null; then
      merge_error "Cannot read UTF-8 original: $original"; exit 1
    fi
    scan_headings "$result"
    match=-1
    for index in "${!HEADING_LINES[@]}"; do
      if [[ "${HEADING_LEVELS[$index]}" == "$level" && "${HEADING_TITLES[$index]}" == "$title" ]]; then
        match=$index; break
      fi
    done
    next="$work_dir/next"
    if (( match >= 0 )); then
      start="${HEADING_LINES[$match]}"
      end=$((LINE_COUNT + 1))
      for (( index=match+1; index<${#HEADING_LINES[@]}; index++ )); do
        if (( HEADING_LEVELS[index] <= level )); then end="${HEADING_LINES[$index]}"; break; fi
      done
      old_section="$work_dir/old-section"
      head -n "$((end - 1))" "$result" | tail -n "+$start" > "$old_section"
      scan_headings "$old_section"
      existing_blanks=$((LINE_COUNT - LAST_CONTENT_LINE))
      {
        head -n "$((start - 1))" "$result"
        if (( source_blanks > 0 )); then
          cat "$section"
        else
          head -n "$core_lines" "$section"
          if (( existing_blanks > 0 )); then tail -n "$existing_blanks" "$old_section"; fi
        fi
        tail -n "+$end" "$result"
      } > "$next"
    else
      cp "$result" "$next"
      if [[ -s "$next" ]]; then
        ensure_final_newline "$next"
        if ! cmp -s <(tail -c 2 "$next") <(printf '\n\n') && ! cmp -s <(tail -c 3 "$next") <(printf '\n\r\n'); then
          printf '\n' >> "$next"
        fi
      fi
      cat "$section" >> "$next"
    fi
    mv -f "$next" "$result"
  done
  cp "$result" "$output"
)

# Keep whole-answer confirmation; the template confirm helper accepts prefixes.
confirm_write() {
  local reply='' IFS=''
  ask reply "$1 [y/N]"
  [[ "$reply" =~ ^[Yy]$ ]] || return 1
  confirm "$1" <<< "$reply" >/dev/null
}

expand_destination_path() {
  local input="$1"
  case "$input" in
    '~') EXPANDED_PATH="$HOME" ;;
    '~/'*) EXPANDED_PATH="$HOME/${input:2}" ;;
    /*) EXPANDED_PATH="$input" ;;
    *)
      printf 'Use an absolute path or a path beginning with "~/".\n' >&2
      return 1
      ;;
  esac
}

add_destination() {
  local label="$1" input="$2" existing source_file parent index
  if ! expand_destination_path "$input"; then return 1; fi
  if [[ "$input" == */ ]]; then
    printf 'That path is a directory path. Enter a file path instead: %s\n' "$EXPANDED_PATH" >&2
    return 1
  fi
  if [[ ! -L "$EXPANDED_PATH" && -d "$EXPANDED_PATH" ]]; then
    printf 'That path is a directory. Enter a file path instead: %s\n' "$EXPANDED_PATH" >&2
    return 1
  fi
  if [[ ! -L "$EXPANDED_PATH" && -e "$EXPANDED_PATH" && ! -f "$EXPANDED_PATH" ]]; then
    printf 'That path is not a regular file. Enter a file path instead: %s\n' "$EXPANDED_PATH" >&2
    return 1
  fi
  parent="$(dirname "$EXPANDED_PATH")"
  if [[ -e "$parent" && ! -d "$parent" ]]; then
    printf 'The parent path is not a directory. Enter a file path under a directory: %s\n' "$EXPANDED_PATH" >&2
    return 1
  fi
  if [[ "$EXPANDED_PATH" == "$BASE_PROMPT" ]]; then
    printf 'Cannot use a source prompt as an output destination: %s\n' "$EXPANDED_PATH" >&2
    return 1
  fi
  for (( index=0; index<${#ASIDE_FILES[@]}; index++ )); do
    source_file="${ASIDE_FILES[$index]}"
    if [[ "$EXPANDED_PATH" == "$source_file" ]]; then
      printf 'Cannot use a source prompt as an output destination: %s\n' "$EXPANDED_PATH" >&2
      return 1
    fi
  done
  for (( index=0; index<${#DEST_PATHS[@]}; index++ )); do
    existing="${DEST_PATHS[$index]}"
    if [[ "$existing" == "$EXPANDED_PATH" ]]; then
      printf 'Already selected: %s\n' "$EXPANDED_PATH"
      return 0
    fi
  done
  DEST_NAMES+=("$label")
  DEST_PATHS+=("$EXPANDED_PATH")
}

select_destinations() {
  local choice token index number valid duplicate existing selected_index
  local -a tokens
  SELECTED=()
  CUSTOM_SELECTED=false
  say 'Choose one or more destinations:'
  for index in "${!TARGET_NAMES[@]}"; do printf '  %d) %s → %s\n' "$((index + 1))" "${TARGET_NAMES[$index]}" "${TARGET_PATHS[$index]}"; done
  printf '  5) Add a custom file path\n'
  printf 'Enter numbers separated by commas, or "all" for presets 1–4.\n'
  while true; do
    ask choice '>'
    SELECTED=()
    CUSTOM_SELECTED=false
    if [[ "$choice" == all ]]; then
      for index in "${!TARGET_NAMES[@]}"; do SELECTED+=("$index"); done
      return
    fi
    if [[ -z "$choice" ]]; then printf 'Choose at least one destination.\n'; continue; fi
    IFS=',' read -r -a tokens <<< "$choice"
    valid=true
    for token in "${tokens[@]}"; do
      token="${token//[[:space:]]/}"
      if [[ ! "$token" =~ ^[0-9]+$ ]]; then
        valid=false
        break
      fi
      number=$((10#$token))
      if (( number < 1 || number > 5 )); then
        valid=false
        break
      fi
      if (( number == 5 )); then
        CUSTOM_SELECTED=true
        continue
      fi
      index=$((number - 1))
      duplicate=false
      for (( selected_index=0; selected_index<${#SELECTED[@]}; selected_index++ )); do
        existing="${SELECTED[$selected_index]}"
        if [[ "$existing" == "$index" ]]; then duplicate=true; fi
      done
      if [[ "$duplicate" == false ]]; then SELECTED+=("$index"); fi
    done
    if [[ "$valid" == true ]]; then return; fi
    printf 'Invalid selection. Enter one or more numbers from 1 to 5.\n'
  done
}

select_many() {
  local title="$1" allow_empty="$2" choice token index number valid duplicate existing selected_index
  shift 2
  local -a options=("$@") tokens
  SELECTED=()
  say "$title"
  for (( index=0; index<${#options[@]}; index++ )); do printf '  %d) %s\n' "$((index + 1))" "${options[$index]}"; done
  if [[ "$allow_empty" == true ]]; then
    printf 'Enter numbers separated by commas, "all", or press Enter for none.\n'
  else
    printf 'Enter numbers separated by commas, or "all".\n'
  fi
  while true; do
    ask choice '>'
    SELECTED=()
    if [[ "$choice" == all ]]; then
      for (( index=0; index<${#options[@]}; index++ )); do SELECTED+=("$index"); done
      return
    fi
    if [[ -z "$choice" && "$allow_empty" == true ]]; then return; fi
    if [[ -z "$choice" ]]; then printf 'Choose at least one item.\n'; continue; fi
    IFS=',' read -r -a tokens <<< "$choice"
    valid=true
    for token in "${tokens[@]}"; do
      token="${token//[[:space:]]/}"
      if [[ ! "$token" =~ ^[0-9]+$ ]]; then valid=false; break; fi
      number=$((10#$token))
      if (( number < 1 || number > ${#options[@]} )); then valid=false; break; fi
      index=$((number - 1))
      duplicate=false
      for (( selected_index=0; selected_index<${#SELECTED[@]}; selected_index++ )); do
        existing="${SELECTED[$selected_index]}"
        if [[ "$existing" == "$index" ]]; then duplicate=true; fi
      done
      if [[ "$duplicate" == false ]]; then SELECTED+=("$index"); fi
    done
    if [[ "$valid" == true ]]; then return; fi
    printf 'Invalid selection. Use the listed numbers, separated by commas.\n'
  done
}

# Sourcing exposes the merge functions without starting the interactive wizard.
if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then return 0; fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BASE_PROMPT="$REPO_ROOT/.agents/AGENTS.md"
ASIDE_DIR="$REPO_ROOT/aside"

if [[ ! -t 0 ]]; then
  printf 'Run this prompt generator in an interactive terminal.\n' >&2
  exit 1
fi

WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/agent-prompt.XXXXXX")"
target_tmp=''
cleanup() {
  rm -rf "$WORK_DIR"
  if [[ -n "$target_tmp" ]]; then rm -f "$target_tmp"; fi
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
ENV_FILE="$WORK_DIR/input-defaults"
# The library needs terminal clearing; fall back to ANSI capabilities for dumb PTYs.
if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && ! tput clear >/dev/null 2>&1; then
  export TERM=xterm
fi

TARGET_NAMES=("Claude" "Codex" "Shared agents" "DSH")
TARGET_PATHS=(
  "$HOME/.claude/CLAUDE.md"
  "$HOME/.codex/AGENTS.md"
  "$HOME/.agents/AGENTS.md"
  "$HOME/.dsh/AGENTS.md"
)
ASIDE_FILES=()
for file in "$ASIDE_DIR"/*/*.md; do
  [[ -f "$file" ]] && ASIDE_FILES+=("$file")
done

stage 'Choose write mode'
printf '  1) Replace with shared instructions and selected aside files (default)\n'
printf '  2) Append selected aside sections to existing regular files only\n'
while true; do
  ask mode_choice 'Write mode [1]:'
  case "$mode_choice" in
    ''|1) WRITE_MODE=replace; break ;;
    2) WRITE_MODE=append; break ;;
    *) printf 'Invalid mode. Enter 1 or 2.\n' ;;
  esac
done
if [[ "$WRITE_MODE" == replace && ! -f "$BASE_PROMPT" ]]; then
  printf 'Shared prompt file not found: %s\n' "$BASE_PROMPT" >&2
  exit 1
fi

stage 'Choose destination agents and paths'
select_destinations
DEST_NAMES=()
DEST_PATHS=()
for (( index=0; index<${#SELECTED[@]}; index++ )); do
  target_index="${SELECTED[$index]}"
  add_destination "${TARGET_NAMES[$target_index]}" "${TARGET_PATHS[$target_index]}"
done
if [[ "$CUSTOM_SELECTED" == true ]]; then
  printf 'Enter a custom output file path (absolute path or ~/path). Existing directories are rejected; a new file may be created at a path that does not exist yet.\n'
  custom_added=false
  while true; do
    ask custom_path 'Custom file path:'
    if [[ -z "$custom_path" ]]; then
      if [[ "$custom_added" == true ]]; then break; fi
      printf 'Option 5 requires a file path. Enter a file path or press Ctrl-C to cancel.\n'
      continue
    fi
    if add_destination 'Custom' "$custom_path"; then custom_added=true; fi
  done
fi
if (( ${#DEST_PATHS[@]} == 0 )); then
  printf 'Choose at least one preset or custom destination.\n' >&2
  exit 1
fi

stage 'Choose aside files'
ASIDE_OPTIONS=()
for (( index=0; index<${#ASIDE_FILES[@]}; index++ )); do
  file="${ASIDE_FILES[$index]}"
  ASIDE_OPTIONS+=("${file#"$ASIDE_DIR/"}")
done
if [[ "$WRITE_MODE" == append ]]; then
  aside_title='Choose aside files to append or replace matching sections; shared instructions will not be added:'
else
  aside_title='The shared behavior prompt is always included. Choose optional aside files:'
fi
if (( ${#ASIDE_OPTIONS[@]} == 0 )); then
  select_many "$aside_title" true
else
  select_many "$aside_title" true "${ASIDE_OPTIONS[@]}"
fi
SELECTED_ASIDE_FILES=()
for (( index=0; index<${#SELECTED[@]}; index++ )); do
  aside_index="${SELECTED[$index]}"
  SELECTED_ASIDE_FILES+=("${ASIDE_FILES[$aside_index]}")
done
if [[ "$WRITE_MODE" == append ]]; then
  if (( ${#SELECTED[@]} == 0 )); then
    printf '\nNo aside files selected; no files will be written.\n'
    exit 0
  fi
fi

CONTENT_FILE="$WORK_DIR/content"
if [[ "$WRITE_MODE" == replace ]]; then
  cat "$BASE_PROMPT" > "$CONTENT_FILE"
  for (( index=0; index<${#SELECTED_ASIDE_FILES[@]}; index++ )); do
    file="${SELECTED_ASIDE_FILES[$index]}"
    printf '\n\n' >> "$CONTENT_FILE"
    cat "$file" >> "$CONTENT_FILE"
  done
fi

stage 'Review and write'
printf 'Write mode: %s\nIncluded files:\n' "$WRITE_MODE"
if [[ "$WRITE_MODE" == replace ]]; then printf '  %s\n' "$BASE_PROMPT"; fi
for (( index=0; index<${#SELECTED_ASIDE_FILES[@]}; index++ )); do
  file="${SELECTED_ASIDE_FILES[$index]}"
  printf '  %s\n' "$file"
done
printf '\nDestinations:\n'
DEST_CONTENTS=()
DEST_SNAPSHOTS=()
SKIPPED_PATHS=()
for index in "${!DEST_PATHS[@]}"; do
  target="${DEST_PATHS[$index]}"
  DEST_CONTENTS+=("")
  DEST_SNAPSHOTS+=("")
  printf '  %s → %s\n' "${DEST_NAMES[$index]}" "$target"
  if [[ "$WRITE_MODE" == append ]]; then
    if [[ -L "$target" ]]; then
      printf '    (symbolic link; append mode skips this destination)\n'
      SKIPPED_PATHS+=("$target")
      continue
    fi
    if [[ ! -e "$target" ]]; then
      printf '    (does not exist; append mode skips this destination)\n'
      SKIPPED_PATHS+=("$target")
      continue
    fi
    if [[ ! -f "$target" ]]; then printf 'Destination is not a regular file: %s\n' "$target" >&2; exit 1; fi
    snapshot="$WORK_DIR/snapshot.$index"
    content="$WORK_DIR/content.$index"
    cp -p "$target" "$snapshot"
    if (( ${#SELECTED_ASIDE_FILES[@]} == 0 )); then
      merge_sections "$snapshot" "$content"
    else
      merge_sections "$snapshot" "$content" "${SELECTED_ASIDE_FILES[@]}"
    fi
    DEST_CONTENTS[$index]="$content"
    DEST_SNAPSHOTS[$index]="$snapshot"
    printf '    (existing regular file; matching sections will be replaced, other content retained)\n'
  else
    DEST_CONTENTS[$index]="$CONTENT_FILE"
    if [[ -L "$target" ]]; then
      printf '    (symbolic link; replacement will make this path a regular file and leave its target unchanged)\n'
    elif [[ -e "$target" ]]; then
      if [[ ! -f "$target" ]]; then printf 'Destination is not a regular file: %s\n' "$target" >&2; exit 1; fi
      printf '    (file exists; you will choose whether to replace it)\n'
    else
      printf '    (new file)\n'
    fi
  fi
  printf '\nPreview for %s (%s bytes):\n\n' "$target" "$(wc -c < "${DEST_CONTENTS[$index]}" | tr -d '[:space:]')"
  cat "${DEST_CONTENTS[$index]}"
  printf '\n'
done

WRITE_PATHS=()
WRITE_ACTIONS=()
WRITE_CONTENTS=()
WRITE_SNAPSHOTS=()
for index in "${!DEST_PATHS[@]}"; do
  target="${DEST_PATHS[$index]}"
  if [[ -z "${DEST_CONTENTS[$index]}" ]]; then continue; fi
  if [[ "$WRITE_MODE" == append ]]; then
    action=append
    prompt="Append selected aside sections to $target?"
  elif [[ -L "$target" ]]; then
    action=replace-link
    prompt="Replace symbolic link $target with a regular file? Its linked target will remain unchanged."
  elif [[ -e "$target" ]]; then
    action=replace
    prompt="Replace existing file $target?"
  else
    action=create
    prompt="Create new file $target?"
  fi
  if confirm_write "$prompt"; then
    WRITE_PATHS+=("$target")
    WRITE_ACTIONS+=("$action")
    WRITE_CONTENTS+=("${DEST_CONTENTS[$index]}")
    WRITE_SNAPSHOTS+=("${DEST_SNAPSHOTS[$index]}")
  else
    SKIPPED_PATHS+=("$target")
  fi
done
if (( ${#SKIPPED_PATHS[@]} > 0 )); then
  printf '\nWill leave unchanged:\n'
  for target in "${SKIPPED_PATHS[@]}"; do printf '  %s\n' "$target"; done
fi
if (( ${#WRITE_PATHS[@]} == 0 )); then
  printf '\nNo destinations were selected for writing.\n'
  exit 0
fi

for index in "${!WRITE_PATHS[@]}"; do
  target="${WRITE_PATHS[$index]}"
  action="${WRITE_ACTIONS[$index]}"
  content="${WRITE_CONTENTS[$index]}"
  snapshot="${WRITE_SNAPSHOTS[$index]}"
  if [[ "$action" == replace-link && ! -L "$target" ]]; then
    printf 'The symbolic link changed after review; refusing to replace it: %s\n' "$target" >&2
    exit 1
  fi
  if [[ "$action" != replace-link && -L "$target" ]]; then
    printf 'Destination became a symbolic link after review: %s\n' "$target" >&2
    exit 1
  fi
  if [[ ! -L "$target" && -e "$target" && ! -f "$target" ]]; then
    printf 'Destination is no longer a regular file: %s\n' "$target" >&2
    exit 1
  fi
  if [[ "$action" == create && ( -e "$target" || -L "$target" ) ]]; then
    printf 'Destination appeared after review; refusing to replace it: %s\n' "$target" >&2
    exit 1
  fi
  target_dir="$(dirname "$target")"
  mkdir -p "$target_dir"
  target_tmp="$(mktemp "$target_dir/.agent-prompt.XXXXXX")"
  if ! cp "$content" "$target_tmp"; then rm -f "$target_tmp"; printf 'Failed to prepare destination: %s\n' "$target" >&2; exit 1; fi
  if [[ "$action" == append ]]; then
    permissions="$(stat -c '%a' "$snapshot" 2>/dev/null || stat -f '%Lp' "$snapshot")"
    chmod "$permissions" "$target_tmp"
    if [[ -L "$target" || ! -f "$target" ]] || ! cmp -s "$snapshot" "$target"; then
      printf 'Destination changed after review; refusing to append: %s\n' "$target" >&2
      exit 1
    fi
  else
    chmod 0644 "$target_tmp"
  fi
  if [[ "$action" == replace-link ]]; then
    link_backup="$(mktemp "$target_dir/.agent-prompt-link.XXXXXX")"
    if ! mv -f "$target" "$link_backup"; then
      rm -f "$link_backup" "$target_tmp"
      printf 'Failed to move the symbolic link before replacement: %s\n' "$target" >&2
      exit 1
    fi
    if ! mv -f "$target_tmp" "$target"; then
      if ! mv -f "$link_backup" "$target"; then
        printf 'Failed to write %s and could not restore its original symbolic link at %s\n' "$target" "$link_backup" >&2
        exit 1
      fi
      rm -f "$target_tmp"
      printf 'Failed to write destination: %s\n' "$target" >&2
      exit 1
    fi
    rm -f "$link_backup"
  elif ! mv -f "$target_tmp" "$target"; then
    rm -f "$target_tmp"
    printf 'Failed to write destination: %s\n' "$target" >&2
    exit 1
  fi
  target_tmp=''
  cmp -s "$content" "$target" || { printf 'Verification failed after writing: %s\n' "$target" >&2; exit 1; }
  printf 'Wrote %s\n' "$target"
done
finish
say 'Prompt generation complete.'
for target in "${WRITE_PATHS[@]}"; do say "Wrote $target"; done
for (( index=0; index<${#SKIPPED_PATHS[@]}; index++ )); do
  target="${SKIPPED_PATHS[$index]}"
  note "Left unchanged: $target"
done
